apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: gjios4nwp-nodejs 
  janus-idp.io/tekton: gjios4nwp-nodejs
  backstage.io/kubernetes-id: gjios4nwp-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gjios4nwp-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  