apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: gjios4nwp-nodejs
  janus-idp.io/tekton: gjios4nwp-nodejs
  backstage.io/kubernetes-id: gjios4nwp-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gjios4nwp-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
