apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: gjios4nwp-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gjios4nwp-nodejs 
  name: gjios4nwp-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: gjios4nwp-nodejs 
